# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    

permissions:
  contents: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env: 
  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Bun
        # You may pin to the exact commit or the version.
        # uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
        uses: oven-sh/setup-bun@v2
        with:
          # The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)
          bun-version: latest
      - run: bun i
      
      - name: Build
        run: bun run build
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          bunx gh-pages -d dist "-u github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
